import {
  ACTIVE_SESSION_KEY,
  AUTO_PB_DETECTION_IN_PROGRAMS_ENABLED_KEY,
  AUTO_REST_TIMERS_ENABLED_KEY,
  COMPLETED_SESSIONS_KEY,
  CONDITIONING_WORKOUT_LOGS_KEY,
  CUSTOM_SET_COUNTS_KEY,
  EXERCISE_SWAPS_KEY,
  FAVORITE_ARTICLES_KEY,
  FAVORITE_PARTNERS_KEY,
  FAVORITE_WORKOUTS_KEY,
  ONBOARDED_KEY,
  ONBOARDING_PROFILE_KEY,
  PROGRAM_COOLDOWN_MODULE_ENABLED_KEY,
  PROGRAM_SESSION_SHIFTS_KEY,
  PROGRAM_SESSION_STATUSES_KEY,
  PROGRAM_START_DATE_KEY,
  PROGRAM_STORAGE_KEY,
  PROGRAM_WARMUP_MODULE_ENABLED_KEY,
  PROGRAM_WORKOUT_WEEKDAYS_KEY,
  PROMO_PRO_GRANT_KEY,
  REST_TIMER_KEY,
  STANDALONE_WORKOUT_LOGS_KEY,
  SWAP_COUNT_STATE_KEY,
  TRAINING_MAXES_KEY,
  WEIGHT_UNIT_KEY,
  WORKOUT_NOTES_KEY,
} from '@/src/utils/storage/keys';

export const TRACKED_METRICS_STORAGE_KEY = 'tracked_metrics';
export const STREAK_STATE_STORAGE_KEY = 'streak_state_v1';

export const SYNCED_KEYS = new Set<string>([
  PROGRAM_STORAGE_KEY,
  PROGRAM_START_DATE_KEY,
  PROGRAM_WORKOUT_WEEKDAYS_KEY,
  PROGRAM_SESSION_SHIFTS_KEY,
  EXERCISE_SWAPS_KEY,
  // workout_logs: row-synced via SQLite + workout_log_sets (not KV).
  CUSTOM_SET_COUNTS_KEY,
  SWAP_COUNT_STATE_KEY,
  WORKOUT_NOTES_KEY,
  COMPLETED_SESSIONS_KEY,
  PROGRAM_SESSION_STATUSES_KEY,
  CONDITIONING_WORKOUT_LOGS_KEY,
  STANDALONE_WORKOUT_LOGS_KEY,
  // personal_bests: row-synced via SQLite + personal_best_entries (not KV).
  TRAINING_MAXES_KEY,
  FAVORITE_WORKOUTS_KEY,
  FAVORITE_ARTICLES_KEY,
  FAVORITE_PARTNERS_KEY,
  WEIGHT_UNIT_KEY,
  AUTO_REST_TIMERS_ENABLED_KEY,
  AUTO_PB_DETECTION_IN_PROGRAMS_ENABLED_KEY,
  PROGRAM_WARMUP_MODULE_ENABLED_KEY,
  PROGRAM_COOLDOWN_MODULE_ENABLED_KEY,
  PROMO_PRO_GRANT_KEY,
  ONBOARDED_KEY,
  ONBOARDING_PROFILE_KEY,
  TRACKED_METRICS_STORAGE_KEY,
  STREAK_STATE_STORAGE_KEY,
]);

export function shouldSync(key: string): boolean {
  return SYNCED_KEYS.has(key);
}

// Kept explicit to document intentionally device-local workout state.
export const DEVICE_ONLY_WORKOUT_KEYS = new Set([
  REST_TIMER_KEY,
  ACTIVE_SESSION_KEY,
]);
