import { BorderRadius, Colors, FontSize, Spacing } from '@/src/constants/theme';
import { StyleSheet } from 'react-native';

export const articleScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.backgroundScreen,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: Spacing.xxl,
    paddingVertical: Spacing.xl,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.06)',
    backgroundColor: 'rgba(255,255,255,0.018)',
  },
  headerBackButton: {
    padding: Spacing.xs,
  },
  headerTitle: {
    color: Colors.accent,
    fontSize: FontSize.sm,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.96,
  },
  headerSpacer: {
    width: 32,
  },
  scrollView: {
    flex: 1,
  },
  content: {
    paddingBottom: 32,
  },
  heroImage: {
    width: '100%',
    height: 220,
    backgroundColor: 'rgba(255,255,255,0.045)',
  },
  metaContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xl,
    paddingHorizontal: Spacing.xxxl,
    paddingTop: Spacing.xxxl,
  },
  categoryBadge: {
    backgroundColor: Colors.accentSoft,
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.xs,
    borderRadius: BorderRadius.xxl,
    borderWidth: 1,
    borderColor: 'rgba(201,150,58,0.28)',
  },
  categoryText: {
    color: Colors.accent,
    fontSize: FontSize.sm,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  readTime: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
  },
  readTimeText: {
    color: Colors.textMuted,
    fontSize: FontSize.base,
  },
  title: {
    color: Colors.textPrimary,
    fontSize: FontSize.hero,
    fontWeight: '900',
    lineHeight: 44,
    paddingHorizontal: Spacing.xxxl,
    marginTop: Spacing.xxl,
  },
  subtitle: {
    color: Colors.textMuted,
    fontSize: FontSize.xxl,
    lineHeight: 24,
    paddingHorizontal: Spacing.xxxl,
    marginTop: Spacing.md,
  },
  readOnWebButton: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    gap: Spacing.xs,
    marginTop: Spacing.xl,
    marginHorizontal: Spacing.xxxl,
    paddingHorizontal: Spacing.xl,
    paddingVertical: Spacing.md,
    borderRadius: BorderRadius.xxl,
    backgroundColor: 'rgba(255,255,255,0.045)',
    borderWidth: 1,
    borderColor: Colors.borderDefault,
  },
  readOnWebText: {
    color: Colors.accent,
    fontSize: FontSize.lg,
    fontWeight: '600',
  },
  divider: {
    height: 1,
    backgroundColor: Colors.borderDefault,
    marginHorizontal: Spacing.xxxl,
    marginVertical: Spacing.section,
  },
  articleContent: {
    paddingHorizontal: Spacing.xxxl,
  },
  heading2: {
    color: Colors.accent,
    fontSize: FontSize.displayLg,
    fontWeight: '900',
    marginTop: Spacing.section,
    marginBottom: Spacing.xl,
  },
  heading3: {
    color: Colors.textPrimary,
    fontSize: FontSize.xxxl,
    fontWeight: '700',
    marginTop: Spacing.xxl,
    marginBottom: Spacing.md,
  },
  paragraph: {
    color: Colors.textSecondary,
    fontSize: FontSize.xxl,
    lineHeight: 26,
    marginBottom: Spacing.xs,
  },
  inlineBold: {
    color: Colors.textPrimary,
    fontWeight: '700',
  },
  listItem: {
    flexDirection: 'row',
    marginBottom: Spacing.md,
    paddingLeft: Spacing.md,
  },
  bullet: {
    color: Colors.accent,
    fontSize: FontSize.xxl,
    lineHeight: 26,
    marginRight: Spacing.xl,
  },
  numberBullet: {
    color: Colors.accent,
    fontSize: FontSize.xxl,
    fontWeight: '600',
    lineHeight: 26,
    marginRight: Spacing.md,
    width: 24,
  },
  listText: {
    flex: 1,
    color: Colors.textSecondary,
    fontSize: FontSize.xxl,
    lineHeight: 26,
  },
  spacer: {
    height: Spacing.xl,
  },
  bottomSpacer: {
    height: 40,
  },
  errorContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  errorText: {
    color: Colors.textMuted,
    fontSize: FontSize.displaySm,
    marginBottom: Spacing.xxl,
  },
  backButton: {
    backgroundColor: Colors.accentSoft,
    paddingHorizontal: Spacing.xxxl,
    paddingVertical: Spacing.lg,
    borderRadius: BorderRadius.xxl,
    borderWidth: 1,
    borderColor: 'rgba(201,150,58,0.28)',
  },
  backButtonText: {
    color: Colors.accent,
    fontSize: FontSize.lg,
    fontWeight: '700',
  },
});
