import { BorderRadius, Colors, FontSize, Spacing } from '@/src/constants/theme';
import { StyleSheet } from 'react-native';

export const articleCardStyles = StyleSheet.create({
  favoriteButton: {
    position: 'absolute',
    top: Spacing.lg,
    right: Spacing.lg,
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.overlayLighter,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
  },
  heroCard: {
    borderRadius: BorderRadius.xxl,
    overflow: 'hidden',
    marginBottom: Spacing.xxl,
    borderWidth: 1,
    borderColor: Colors.borderDefault,
    shadowColor: '#000000',
    shadowOpacity: 0.28,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 12 },
    elevation: 4,
  },
  heroImage: {
    height: 240,
    justifyContent: 'flex-end',
  },
  heroImageStyle: {
    borderRadius: BorderRadius.xxl,
  },
  heroOverlay: {
    flex: 1,
    backgroundColor: Colors.overlayLight,
    padding: Spacing.xxl,
    justifyContent: 'space-between',
  },
  heroBadgeRow: {
    flexDirection: 'row',
    gap: Spacing.md,
  },
  categoryBadge: {
    backgroundColor: Colors.accentSoft,
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.xs,
    borderRadius: BorderRadius.xxl,
    borderWidth: 1,
    borderColor: 'rgba(201,150,58,0.28)',
  },
  categoryBadgeText: {
    color: Colors.accent,
    fontSize: FontSize.sm,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  featuredBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
    backgroundColor: Colors.accent,
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.xs,
    borderRadius: BorderRadius.sm,
  },
  featuredBadgeText: {
    color: Colors.textOnAccent,
    fontSize: FontSize.sm,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  heroContent: {
    gap: Spacing.md,
  },
  heroTitle: {
    color: Colors.textPrimary,
    fontSize: FontSize.displayLg,
    fontWeight: '800',
    lineHeight: 28,
  },
  heroSubtitle: {
    color: Colors.textSecondary,
    fontSize: FontSize.lg,
    lineHeight: 20,
  },
  heroMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
    marginTop: Spacing.xs,
  },
  heroMetaText: {
    color: Colors.textMuted,
    fontSize: FontSize.md,
    fontWeight: '500',
  },
  compactCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#151517',
    borderRadius: BorderRadius.xxl,
    padding: Spacing.xl,
    marginBottom: Spacing.lg,
    borderWidth: 1,
    borderColor: Colors.borderDefault,
    shadowColor: '#000000',
    shadowOpacity: 0.2,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  compactImage: {
    width: 72,
    height: 72,
    borderRadius: BorderRadius.xxl,
    backgroundColor: 'rgba(255,255,255,0.045)',
  },
  compactContent: {
    flex: 1,
    marginLeft: Spacing.xl,
    gap: Spacing.xs,
  },
  compactCategoryRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  compactCategory: {
    color: Colors.accent,
    fontSize: FontSize.sm,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.96,
  },
  compactTitle: {
    color: Colors.textPrimary,
    fontSize: FontSize.xl,
    fontWeight: '900',
    lineHeight: 20,
  },
  compactMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
  },
  compactMetaText: {
    color: Colors.textPlaceholder,
    fontSize: FontSize.md,
  },
  horizontalCard: {
    width: 200,
    borderRadius: BorderRadius.xxl,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: Colors.borderDefault,
    shadowColor: '#000000',
    shadowOpacity: 0.22,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 9 },
    elevation: 3,
  },
  horizontalImage: {
    height: 150,
    justifyContent: 'flex-end',
  },
  horizontalImageStyle: {
    borderRadius: BorderRadius.xxl,
  },
  horizontalOverlay: {
    flex: 1,
    backgroundColor: Colors.overlayLighter,
    padding: Spacing.xl,
    justifyContent: 'space-between',
  },
  horizontalCategoryBadge: {
    alignSelf: 'flex-start',
    backgroundColor: Colors.accentOverlay,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.xxs,
    borderRadius: BorderRadius.sm,
  },
  horizontalCategoryText: {
    color: Colors.textOnAccent,
    fontSize: FontSize.xxs,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  horizontalContent: {
    gap: Spacing.xs,
  },
  horizontalTitle: {
    color: Colors.textPrimary,
    fontSize: FontSize.lg,
    fontWeight: '700',
    lineHeight: 18,
  },
  horizontalMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
  },
  horizontalMetaText: {
    color: Colors.textTertiary,
    fontSize: FontSize.sm,
    fontWeight: '500',
  },
});
