import { StyleSheet } from 'react-native';
import { BorderRadius, Colors, FontSize, Spacing } from '@/src/constants/theme';

export const iCloudSyncConflictModalStyles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: Colors.overlay,
    paddingHorizontal: Spacing.xxl,
    paddingVertical: Spacing.section,
    justifyContent: 'center',
  },
  card: {
    backgroundColor: '#151517',
    borderRadius: BorderRadius.xxl,
    borderWidth: 1,
    borderColor: Colors.borderDefault,
    paddingHorizontal: Spacing.xxl,
    paddingTop: Spacing.xxl,
    paddingBottom: Spacing.section,
    maxHeight: '88%',
    shadowColor: '#000000',
    shadowOpacity: 0.32,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 12 },
    elevation: 5,
  },
  headerIconWrap: {
    width: 44,
    height: 44,
    borderRadius: BorderRadius.xxl,
    backgroundColor: Colors.accentSoft,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'flex-start',
    marginBottom: Spacing.xl,
  },
  title: {
    color: Colors.textPrimary,
    fontSize: FontSize.displayLg,
    fontWeight: '800',
    letterSpacing: -0.4,
    marginBottom: Spacing.sm,
  },
  subtitle: {
    color: Colors.textMuted,
    fontSize: FontSize.lg,
    lineHeight: 22,
    marginBottom: Spacing.xxl,
  },
  comparisonCard: {
    flexDirection: 'row',
    gap: Spacing.md,
    marginBottom: Spacing.xxl,
  },
  comparisonHalf: {
    flex: 1,
    backgroundColor: 'rgba(255,255,255,0.045)',
    borderRadius: BorderRadius.xxl,
    borderWidth: 1,
    borderColor: Colors.borderDefault,
    padding: Spacing.xl,
  },
  comparisonHalfAccent: {
    borderColor: Colors.accent,
    backgroundColor: Colors.accentSoft,
  },
  comparisonLabel: {
    color: Colors.textMuted,
    fontSize: FontSize.sm,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    marginBottom: Spacing.sm,
  },
  comparisonTime: {
    color: Colors.textPrimary,
    fontSize: FontSize.lg,
    fontWeight: '700',
    lineHeight: 20,
  },
  comparisonHint: {
    color: Colors.textTertiary,
    fontSize: FontSize.base,
    marginTop: Spacing.sm,
    lineHeight: 18,
  },
  sectionLabel: {
    color: Colors.textSecondary,
    fontSize: FontSize.md,
    fontWeight: '700',
    marginBottom: Spacing.md,
  },
  keyList: {
    maxHeight: 220,
    marginBottom: Spacing.xl,
  },
  keyListContent: {
    paddingBottom: Spacing.sm,
  },
  keyRow: {
    paddingVertical: Spacing.md,
    paddingHorizontal: Spacing.xl,
    borderRadius: BorderRadius.xxl,
    backgroundColor: 'rgba(255,255,255,0.045)',
    borderWidth: 1,
    borderColor: Colors.borderDefault,
    marginBottom: Spacing.md,
  },
  keyRowTitle: {
    color: Colors.textPrimary,
    fontSize: FontSize.lg,
    fontWeight: '700',
    marginBottom: Spacing.xs,
  },
  keyRowMeta: {
    color: Colors.textMuted,
    fontSize: FontSize.base,
    lineHeight: 20,
  },
  body: {
    color: Colors.textSecondary,
    fontSize: FontSize.md,
    marginBottom: Spacing.md,
    lineHeight: 20,
  },
  actions: {
    flexDirection: 'row',
    gap: Spacing.md,
    marginTop: Spacing.sm,
  },
  button: {
    flex: 1,
    paddingVertical: Spacing.xl,
    borderRadius: BorderRadius.xxl,
    alignItems: 'center',
    borderWidth: 1,
  },
  primaryButton: {
    backgroundColor: Colors.accentSoft,
    borderColor: Colors.accent,
  },
  primaryButtonText: {
    color: Colors.accent,
    fontSize: FontSize.xxl,
    fontWeight: '700',
  },
  secondaryButton: {
    backgroundColor: 'rgba(255,255,255,0.045)',
    borderColor: Colors.borderDefault,
  },
  secondaryButtonText: {
    color: Colors.textPrimary,
    fontSize: FontSize.xxl,
    fontWeight: '700',
  },
});
