import { BorderRadius, Colors, FontSize, Spacing } from '@/src/constants/theme';
import { StyleSheet } from 'react-native';

export const workoutScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.backgroundScreen,
  },
  movingSessionOverlay: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    backgroundColor: Colors.overlay,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
  },
  movingSessionOverlayCard: {
    backgroundColor: '#151517',
    borderRadius: BorderRadius.xxl,
    borderWidth: 1,
    borderColor: Colors.borderDefault,
    paddingVertical: Spacing.xxl,
    paddingHorizontal: Spacing.section,
    minWidth: 220,
    alignItems: 'center',
    shadowColor: '#000000',
    shadowOpacity: 0.32,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 5,
  },
  movingSessionOverlayText: {
    color: Colors.textPrimary,
    fontSize: FontSize.xxl,
    fontWeight: '700',
  },
  keyboardAvoidingView: {
    flex: 1,
  },
  scrollView: {
    flex: 1,
  },
  content: {
    padding: Spacing.xxl,
  },
  header: {
    marginBottom: Spacing.section,
    paddingTop: Spacing.xxl,
  },
  headerTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  headerTextContainer: {
    flex: 1,
  },
  sessionCtaRow: {
    marginTop: Spacing.md,
    flexDirection: 'row',
    gap: Spacing.md,
  },
  sessionCtaHalf: {
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: 0,
  },
  headerActions: {
    alignItems: 'flex-end',
    gap: Spacing.sm,
  },
  headerBottomActions: {
    marginTop: Spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: Spacing.sm,
  },
  title: {
    color: Colors.textPrimary,
    fontSize: FontSize.hero,
    fontWeight: '900',
    marginBottom: Spacing.md,
    letterSpacing: -1.1,
    lineHeight: 44,
  },
  subtitle: {
    color: Colors.textMuted,
    fontSize: FontSize.xxl,
    fontWeight: '500',
  },
  description: {
    color: Colors.textSecondary,
    fontSize: FontSize.lg,
    fontWeight: '500',
    marginBottom: Spacing.xl,
    lineHeight: 20,
  },
  moduleToggleRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: Spacing.sm,
    marginTop: Spacing.md,
  },
  moduleToggle: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    borderRadius: BorderRadius.pill,
    backgroundColor: 'rgba(255,255,255,0.045)',
    borderWidth: 1,
    borderColor: Colors.borderDefault,
  },
  moduleToggleActive: {
    backgroundColor: Colors.accentSoft,
    borderColor: Colors.accent,
  },
  moduleToggleText: {
    color: Colors.textMuted,
    fontSize: FontSize.md,
    fontWeight: '700',
  },
  moduleToggleTextActive: {
    color: Colors.textPrimary,
  },
  intensityCard: {
    backgroundColor: '#151517',
    borderRadius: BorderRadius.xxl,
    padding: Spacing.xxl,
    marginBottom: Spacing.xxl,
    borderWidth: 1,
    borderColor: Colors.borderDefault,
    shadowColor: '#000000',
    shadowOpacity: 0.24,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 10 },
    elevation: 4,
  },
  intensityCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Spacing.lg,
  },
  intensityLabel: {
    color: Colors.accent,
    fontSize: FontSize.sm,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.96,
  },
  intensityValue: {
    color: Colors.textPrimary,
    fontSize: FontSize.displayMd,
    fontWeight: '800',
  },
  intensityBarTrack: {
    height: 6,
    borderRadius: BorderRadius.xs,
    backgroundColor: Colors.backgroundSubtle,
    marginBottom: Spacing.xl,
    overflow: 'hidden',
  },
  intensityBarFill: {
    height: '100%',
    borderRadius: BorderRadius.xs,
    backgroundColor: Colors.accent,
  },
  intensityFeel: {
    color: Colors.textSecondary,
    fontSize: FontSize.lg,
    lineHeight: 20,
    marginBottom: Spacing.xl,
  },
  intensityCta: {
    alignSelf: 'flex-start',
  },
  intensityCtaText: {
    color: Colors.accent,
    fontSize: FontSize.lg,
    fontWeight: '600',
  },
  setCurrentDayButton: {
    marginTop: Spacing.xxl,
    backgroundColor: Colors.accentSoft,
    borderRadius: BorderRadius.xxl,
    padding: Spacing.xl,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(201,150,58,0.34)',
  },
  setCurrentDayButtonInHeaderActions: {
    marginTop: 0,
  },
  setCurrentDayButtonText: {
    color: Colors.accent,
    fontSize: FontSize.lg,
    fontWeight: '700',
    letterSpacing: 0.2,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    color: Colors.textPrimary,
    fontSize: FontSize.xxl,
    marginBottom: Spacing.md,
  },
  warmupCard: {
    backgroundColor: '#151517',
    borderRadius: BorderRadius.xxl,
    padding: Spacing.xxl,
    marginBottom: Spacing.xxl,
    borderWidth: 1,
    borderColor: Colors.borderDefault,
    shadowColor: '#000000',
    shadowOpacity: 0.2,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  warmupTitle: {
    color: Colors.accent,
    fontSize: FontSize.sm,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.96,
    marginBottom: Spacing.md,
  },
  warmupDescription: {
    color: Colors.textMuted,
    fontSize: FontSize.lg,
    fontStyle: 'italic',
    marginBottom: Spacing.xl,
    lineHeight: 20,
  },
  warmupList: {
    gap: Spacing.md,
  },
  warmupItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: Spacing.md,
  },
  warmupBullet: {
    color: Colors.accent,
    fontSize: FontSize.lg,
    fontWeight: '600',
    marginTop: 1,
  },
  warmupText: {
    color: Colors.textSecondaryAlt,
    fontSize: FontSize.lg,
    lineHeight: 20,
    flex: 1,
  },
  notesContainer: {
    backgroundColor: '#151517',
    borderRadius: BorderRadius.xxl,
    marginTop: Spacing.xxl,
    borderWidth: 1,
    borderColor: Colors.borderDefault,
    overflow: 'hidden',
    shadowColor: '#000000',
    shadowOpacity: 0.2,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  notesHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: Spacing.xxl,
  },
  notesTitle: {
    color: Colors.textPrimary,
    fontSize: FontSize.xxl,
    fontWeight: '700',
  },
  notesHeaderRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
  },
  notesBadge: {
    backgroundColor: Colors.backgroundSubtle,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.xs,
    borderRadius: BorderRadius.sm,
  },
  notesBadgeText: {
    color: Colors.textMuted,
    fontSize: FontSize.md,
    fontWeight: '500',
  },
  notesExpandIcon: {
    color: Colors.textMuted,
    fontSize: FontSize.md,
  },
  notesCopyTopStrip: {
    borderWidth: 1,
    borderColor: Colors.accent,
    borderRadius: BorderRadius.xxl,
    paddingVertical: Spacing.xl,
    alignItems: 'center',
    marginTop: Spacing.md,
    marginBottom: Spacing.xl,
  },
  notesCopyLink: {
    color: Colors.accent,
    fontSize: FontSize.lg,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  notesActionsContainer: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: Colors.borderDefault,
    padding: Spacing.xxl,
    paddingTop: Spacing.xl,
    gap: Spacing.md,
  },
  notesAction: {
    backgroundColor: 'rgba(255,255,255,0.045)',
    borderWidth: 1,
    borderColor: Colors.borderDefault,
    borderRadius: BorderRadius.xxl,
    paddingVertical: Spacing.lg,
    paddingHorizontal: Spacing.xl,
  },
  notesActionText: {
    color: Colors.accent,
    fontSize: FontSize.lg,
    fontWeight: '600',
  },
  keyboardDoneBar: {
    position: 'absolute',
    left: 0,
    right: 0,
    zIndex: 10,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(15,15,17,0.96)',
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: Colors.borderDefault,
    paddingHorizontal: Spacing.xxl,
    paddingVertical: Spacing.lg,
  },
  keyboardDoneBarSpacer: {
    flex: 1,
  },
  keyboardDoneBtn: {
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.sm,
  },
  keyboardDoneText: {
    color: Colors.accent,
    fontSize: FontSize.xl,
    fontWeight: '700',
  },
  notesInput: {
    color: Colors.textPrimary,
    fontSize: FontSize.lg,
    lineHeight: 22,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: Colors.borderDefault,
    padding: Spacing.xxl,
    minHeight: 100,
  },
  startSessionButtonContainer: {
    paddingHorizontal: Spacing.xxl,
    marginTop: Spacing.xl,
  },
  startSessionButton: {
    borderWidth: 1,
    borderColor: 'rgba(201,150,58,0.34)',
    borderRadius: BorderRadius.xxl,
    paddingVertical: Spacing.xl,
    alignItems: 'center',
    backgroundColor: 'rgba(201,150,58,0.1)',
    shadowColor: Colors.accent,
    shadowOpacity: 0.12,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
  },
  startSessionButtonText: {
    color: Colors.accent,
    fontSize: FontSize.lg,
    fontWeight: '800',
    letterSpacing: 0.2,
  },
  completedSessionBanner: {
    backgroundColor: '#151517',
    borderRadius: BorderRadius.xxl,
    padding: Spacing.xxl,
    marginBottom: Spacing.xxl,
    borderWidth: 1,
    borderColor: Colors.borderDefault,
    shadowColor: '#000000',
    shadowOpacity: 0.22,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 10 },
    elevation: 4,
  },
  completedSessionTitle: {
    color: Colors.accent,
    fontSize: FontSize.sm,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.96,
    marginBottom: Spacing.xl,
  },
  completedSessionStats: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: Spacing.xl,
  },
  completedSessionStat: {
    alignItems: 'center',
    flex: 1,
  },
  completedSessionStatValue: {
    color: Colors.textPrimary,
    fontSize: FontSize.displaySm,
    fontWeight: '800',
    marginBottom: Spacing.xxs,
  },
  completedSessionStatLabel: {
    color: Colors.textMuted,
    fontSize: FontSize.sm,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.96,
  },
  redoButton: {
    alignSelf: 'center',
    paddingVertical: Spacing.md,
    paddingHorizontal: Spacing.xxl,
  },
  redoButtonText: {
    color: Colors.textMuted,
    fontSize: FontSize.base,
    fontWeight: '600',
  },
  exportWorkoutButton: {
    marginTop: Spacing.md,
    paddingVertical: Spacing.sm,
  },
  exportWorkoutButtonText: {
    color: Colors.accent,
    fontSize: FontSize.lg,
    fontWeight: '600',
  },
});
