import { BorderRadius, Colors, FontSize, Spacing } from '@/src/constants/theme';
import { StyleSheet } from 'react-native';

export const workoutsListStyles = StyleSheet.create({
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.045)',
    borderRadius: BorderRadius.xxl,
    borderWidth: 1,
    borderColor: Colors.borderDefault,
    marginTop: Spacing.xl,
    marginBottom: Spacing.xxl,
    paddingHorizontal: Spacing.xl,
    height: 44,
  },
  searchIcon: {
    marginRight: Spacing.md,
  },
  searchInput: {
    flex: 1,
    color: Colors.textPrimary,
    fontSize: FontSize.xxl,
    padding: 0,
  },
  filterScrollContent: {
    paddingBottom: Spacing.md,
    gap: Spacing.md,
    paddingRight: Spacing.xxl,
  },
  quickFiltersRow: {
    marginTop: Spacing.sm,
  },
  listContent: {
    paddingTop: Spacing.xxl,
  },
  curatedSection: {
    marginBottom: Spacing.xxl,
  },
  curatedSectionHeader: {
    marginBottom: Spacing.lg,
  },
  curatedSectionTitle: {
    color: Colors.textPrimary,
    fontSize: FontSize.displayXXl,
    fontWeight: '900',
    marginBottom: 4,
    letterSpacing: -0.7,
  },
  curatedSectionHelper: {
    color: Colors.textMuted,
    fontSize: FontSize.xl,
    fontWeight: '400',
    lineHeight: 22,
  },
  curatedScrollContent: {
    gap: Spacing.lg,
    paddingRight: Spacing.xl,
  },
  curatedCard: {
    width: 240,
    minHeight: 168,
    backgroundColor: '#151517',
    borderRadius: BorderRadius.xxl,
    padding: Spacing.xl,
    borderWidth: 1,
    borderColor: Colors.borderDefault,
    justifyContent: 'space-between',
    shadowColor: '#000000',
    shadowOpacity: 0.24,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 10 },
    elevation: 4,
  },
  cardPressed: {
    transform: [{ scale: 0.98 }],
    borderColor: 'rgba(201,150,58,0.34)',
    shadowOpacity: 0.38,
  },
  curatedCardLocked: {
    borderColor: Colors.accent,
    borderWidth: 2,
    opacity: 0.6,
  },
  curatedCardTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: Spacing.md,
  },
  curatedCardCategory: {
    color: Colors.accent,
    fontSize: FontSize.sm,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.96,
  },
  curatedCardProBadge: {
    backgroundColor: Colors.accent,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 2,
    borderRadius: BorderRadius.sm,
  },
  curatedCardProBadgeText: {
    color: Colors.textOnAccent,
    fontSize: FontSize.xxs,
    fontWeight: '700',
  },
  curatedCardTitle: {
    color: Colors.textPrimary,
    fontSize: FontSize.displaySm,
    fontWeight: '900',
    marginBottom: Spacing.md,
    letterSpacing: -0.3,
  },
  curatedCardStats: {
    alignItems: 'flex-start',
    gap: Spacing.sm,
  },
  curatedDurationBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.xs,
    borderRadius: BorderRadius.xxl,
    backgroundColor: Colors.accentSoft,
    borderWidth: 1,
    borderColor: 'rgba(201,150,58,0.22)',
  },
  curatedDurationText: {
    color: Colors.textPrimary,
    fontSize: FontSize.md,
    fontWeight: '900',
    fontVariant: ['tabular-nums'],
  },
  curatedStatLabel: {
    color: Colors.textMuted,
    fontSize: FontSize.xs,
    fontWeight: '800',
    letterSpacing: 0.76,
    textTransform: 'uppercase',
  },
  curatedCardMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
  },
  curatedCardMetaText: {
    color: Colors.textMuted,
    fontSize: FontSize.md,
    fontWeight: '600',
  },
  allWorkoutsHeader: {
    marginTop: Spacing.xxl,
    marginBottom: Spacing.lg,
  },
  allWorkoutsTitle: {
    color: Colors.textPrimary,
    fontSize: FontSize.displayXXl,
    fontWeight: '900',
    letterSpacing: -0.7,
  },
  allWorkoutsHelper: {
    color: Colors.textMuted,
    fontSize: FontSize.xl,
    lineHeight: 22,
    marginTop: 4,
  },
  workoutCard: {
    backgroundColor: '#151517',
    borderRadius: BorderRadius.xxl,
    padding: Spacing.xxl,
    marginBottom: Spacing.xl,
    borderWidth: 1,
    borderColor: Colors.borderDefault,
    shadowColor: '#000000',
    shadowOpacity: 0.22,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 10 },
    elevation: 4,
  },
  sponsorCard: {
    backgroundColor: '#151517',
    borderRadius: BorderRadius.xxl,
    padding: Spacing.xxl,
    marginBottom: Spacing.xl,
    borderWidth: 1,
    borderColor: Colors.accent,
    shadowColor: '#000000',
    shadowOpacity: 0.22,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 9 },
    elevation: 3,
  },
  sponsorTitle: {
    color: Colors.textPrimary,
    fontSize: FontSize.displayMd,
    fontWeight: '800',
    marginBottom: Spacing.sm,
  },
  sponsorDescription: {
    color: Colors.textMuted,
    fontSize: FontSize.lg,
    lineHeight: 20,
    marginBottom: Spacing.lg,
  },
  sponsorLinkRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
  },
  sponsorLinkText: {
    color: Colors.accent,
    fontSize: FontSize.lg,
    fontWeight: '700',
  },
  workoutCardLocked: {
    borderColor: Colors.accent,
    borderWidth: 2,
    opacity: 0.6,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Spacing.md,
  },
  cardTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
  },
  categoryIcon: {
    width: 28,
    height: 28,
    borderRadius: BorderRadius.xxl,
    backgroundColor: Colors.accentSoft,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(201,150,58,0.2)',
  },
  cardCategory: {
    color: Colors.accent,
    fontSize: FontSize.md,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.96,
  },
  premiumBadge: {
    backgroundColor: Colors.accent,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 2,
    borderRadius: BorderRadius.sm,
  },
  premiumBadgeText: {
    color: Colors.textOnAccent,
    fontSize: FontSize.xxs,
    fontWeight: '700',
  },
  favoriteButton: {
    padding: Spacing.xs,
  },
  cardTitle: {
    color: Colors.textPrimary,
    fontSize: FontSize.displayLg,
    fontWeight: '900',
    marginBottom: Spacing.xs,
    letterSpacing: -0.4,
  },
  cardDescription: {
    color: Colors.textMuted,
    fontSize: FontSize.lg,
    lineHeight: 20,
    marginBottom: Spacing.xl,
  },
  cardMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xl,
    marginBottom: Spacing.xl,
  },
  metaItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
  },
  metaText: {
    color: Colors.textMuted,
    fontSize: FontSize.md,
    fontWeight: '500',
  },
  difficultyBadge: {
    paddingHorizontal: Spacing.md,
    paddingVertical: 2,
    borderRadius: BorderRadius.sm,
    borderWidth: 1,
  },
  difficultyText: {
    fontSize: FontSize.sm,
    fontWeight: '600',
  },
  tagsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: Spacing.sm,
  },
  tag: {
    backgroundColor: 'rgba(255,255,255,0.05)',
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.xs,
    borderRadius: BorderRadius.xxl,
    borderWidth: 1,
    borderColor: Colors.borderDefault,
  },
  tagText: {
    color: Colors.textMuted,
    fontSize: FontSize.md,
    fontWeight: '500',
  },
  emptyState: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 48,
  },
  emptyTitle: {
    color: Colors.textPrimary,
    fontSize: FontSize.displayMd,
    fontWeight: '700',
    marginTop: Spacing.xxl,
    marginBottom: Spacing.md,
    textAlign: 'center',
  },
  emptyDescription: {
    color: Colors.textMuted,
    fontSize: FontSize.lg,
    lineHeight: 20,
    textAlign: 'center',
  },
  disciplineSection: {
    height: 184,
    width: 174,
    alignItems: 'flex-start',
    justifyContent: 'flex-end',
    overflow: 'hidden',
    borderRadius: BorderRadius.xxl,
    borderWidth: 1,
    borderColor: Colors.borderDefault,
    padding: Spacing.xl,
    shadowColor: '#000000',
    shadowOpacity: 0.3,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 12 },
    elevation: 4,
  },
  disciplineSectionTitle: {
    color: Colors.textPrimary,
    fontSize: FontSize.displayLg,
    fontWeight: '900',
    textAlign: 'left',
    letterSpacing: -0.4,
  },
  disciplineImage: {
    ...StyleSheet.absoluteFillObject,
  },
  disciplineGoldOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.24)',
  },
  disciplineBottomShade: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: '68%',
    backgroundColor: 'rgba(0,0,0,0.58)',
  },
  disciplineAccentLine: {
    width: 34,
    height: 2,
    borderRadius: 1,
    backgroundColor: Colors.accent,
    marginBottom: Spacing.md,
  },
  disciplineLogo: {
    resizeMode: 'contain',
    marginBottom: Spacing.lg,
  },
  disciplineImageStyle: {
    borderRadius: BorderRadius.xxl,
  },
  disciplineDescription: {
    color: Colors.textMuted,
    fontSize: FontSize.lg,
    lineHeight: 20,
    textAlign: 'center',
    marginBottom: Spacing.xl,
  },
  disciplineLink: {
    color: Colors.accent,
    fontSize: FontSize.lg,
    fontWeight: '700',
  },
  sponsorLogo: {
    width: 18,
    height: 18,
    resizeMode: 'contain',
  },
});
