import { BorderRadius, Colors, FontSize, Spacing } from '@/src/constants/theme';
import { StyleSheet } from 'react-native';

/** Warm wash behind the home welcome strip (brand accent, low alpha). */
const welcomeStripBg = 'rgba(201, 150, 58, 0.12)';

export const homeScreenStyles = StyleSheet.create({
  loadingBox: {
    paddingVertical: Spacing.section,
    alignItems: 'center',
    justifyContent: 'center',
  },
  welcomeStrip: {
    borderRadius: BorderRadius.xxl,
    backgroundColor: welcomeStripBg,
    borderWidth: 1,
    borderColor: Colors.borderDefault,
    paddingVertical: Spacing.xl,
    paddingHorizontal: Spacing.section,
    marginBottom: Spacing.xl,
    shadowColor: Colors.accent,
    shadowOpacity: 0.12,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  welcomeStripTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: Spacing.md,
  },
  /** Keeps headline on the left and badge pinned right when titles wrap. */
  welcomeHeadlineCell: {
    flex: 1,
    marginRight: Spacing.sm,
    minWidth: 0,
  },
  planBadgePro: {
    backgroundColor: Colors.accent,
    paddingHorizontal: Spacing.lg,
    borderRadius: BorderRadius.pill,
    minHeight: 28,
    justifyContent: 'center',
    alignItems: 'center',
  },
  planBadgeFree: {
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: 'rgba(201, 150, 58, 0.45)',
    paddingHorizontal: Spacing.md,
    borderRadius: BorderRadius.pill,
    minHeight: 28,
    justifyContent: 'center',
    alignItems: 'center',
  },
  planBadgeLabelPro: {
    color: Colors.textOnAccent,
    fontSize: FontSize.md,
    fontWeight: '700',
    letterSpacing: 0.85,
  },
  planBadgeLabelFree: {
    color: Colors.accent,
    fontSize: FontSize.xs,
    fontWeight: '800',
    letterSpacing: 0.85,
  },
  welcomeTitle: {
    color: Colors.textPrimary,
    fontSize: FontSize.xl,
    fontWeight: '800',
    letterSpacing: -0.3,
  },
  welcomeBody: {
    color: Colors.textSecondary,
    fontSize: FontSize.xl,
    lineHeight: 22,
    marginTop: Spacing.sm,
    fontWeight: '500',
  },
  /** Remote Sanity notification strip — background/border/colours come from CMS. */
  notificationBanner: {
    alignItems: 'flex-start',
    borderRadius: BorderRadius.xxl,
    borderWidth: 1,
    paddingVertical: Spacing.xxl,
    paddingHorizontal: Spacing.section,
    marginBottom: Spacing.xxl,
    gap: Spacing.sm,
    overflow: 'hidden',
    shadowColor: Colors.accentBronze,
    shadowOpacity: 0.28,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 12 },
    elevation: 5,
  },
  notificationBannerGlowTop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: '48%',
    backgroundColor: 'rgba(255,255,255,0.16)',
    opacity: 0.45,
  },
  notificationBannerBronzeWash: {
    position: 'absolute',
    right: -42,
    bottom: -56,
    width: 190,
    height: 140,
    borderRadius: 70,
    backgroundColor: Colors.accentBronze,
    opacity: 0.28,
  },
  notificationBannerNoise: {
    position: 'absolute',
    top: 10,
    right: 14,
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: 'rgba(255,255,255,0.28)',
    shadowColor: '#FFFFFF',
    shadowOpacity: 0.28,
    shadowRadius: 16,
    shadowOffset: { width: -80, height: 40 },
  },
  notificationBannerTitle: {
    fontSize: FontSize.displayMd,
    fontWeight: '900',
    letterSpacing: -0.4,
    textAlign: 'left',
    width: '100%',
  },
  notificationBannerBody: {
    fontSize: FontSize.base,
    lineHeight: 20,
    fontWeight: '500',
    textAlign: 'left',
    width: '100%',
  },
  notificationCta: {
    paddingHorizontal: Spacing.section,
    paddingVertical: Spacing.md,
    borderRadius: BorderRadius.pill,
    marginTop: Spacing.xs,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
  },
  notificationCtaText: {
    fontSize: FontSize.md,
    fontWeight: '800',
  },
  section: {
    marginBottom: Spacing.xxl,
  },
  sectionheader: {
    marginBottom: Spacing.lg,
    paddingLeft: Spacing.md,
    borderLeftWidth: 1,
    borderLeftColor: Colors.accent,
  },
  sectionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    marginBottom: 4,
  },
  sectionTitle: {
    color: Colors.accent,
    fontSize: FontSize.sm,
    fontWeight: '800',
    flex: 1,
    letterSpacing: 0.96,
    textTransform: 'uppercase',
  },
  sectionSubtitle: {
    color: Colors.textMuted,
    fontSize: FontSize.lg,
    lineHeight: 20,
  },
  card: {
    backgroundColor: '#161618',
    borderRadius: BorderRadius.xxl,
    borderWidth: 1,
    borderColor: Colors.borderDefault,
    padding: Spacing.xxl,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
    shadowColor: '#000000',
    shadowOpacity: 0.28,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 10 },
    elevation: 4,
  },
  cardPressed: {
    transform: [{ scale: 0.98 }],
    borderColor: 'rgba(201,150,58,0.34)',
    shadowOpacity: 0.4,
  },
  cardBody: {
    flex: 1,
    gap: Spacing.sm,
  },
  cardChevronWrap: {
    justifyContent: 'center',
    alignItems: 'center',
    width: 34,
    height: 34,
    borderRadius: 12,
    backgroundColor: Colors.accentSoft,
  },
  cardTitle: {
    color: Colors.textPrimary,
    fontSize: FontSize.displaySm,
    fontWeight: '900',
    letterSpacing: -0.3,
  },
  cardMuted: {
    color: Colors.textMuted,
    fontSize: FontSize.lg,
    fontWeight: '400',
  },
  cardAccent: {
    color: Colors.accent,
    fontWeight: '400',
  },
  emptyTitle: {
    color: Colors.textPrimary,
    fontSize: FontSize.xl,
    fontWeight: '800',
  },
  emptySubtitle: {
    color: Colors.textMuted,
    fontSize: FontSize.lg,
    fontWeight: '400',
    marginTop: Spacing.xs,
  },
  pbRow: {
    marginTop: Spacing.sm,
    paddingVertical: Spacing.md,
    paddingHorizontal: Spacing.lg,
    borderWidth: 1,
    borderColor: Colors.borderDefault,
    borderRadius: BorderRadius.xxl,
    backgroundColor: 'rgba(255,255,255,0.035)',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: Spacing.md,
  },
  pbRowFirst: {
    marginTop: 0,
  },
  pbRowTextCell: {
    flex: 1,
    minWidth: 0,
  },
  pbRowTitle: {
    color: Colors.textPrimary,
    fontSize: FontSize.lg,
    fontWeight: '800',
  },
  pbRowMeta: {
    color: Colors.accent,
    fontSize: FontSize.xs,
    fontWeight: '800',
    marginTop: Spacing.xxs,
    letterSpacing: 0.76,
    textTransform: 'uppercase',
  },
  pbValueChip: {
    paddingVertical: Spacing.sm,
    paddingHorizontal: Spacing.lg,
    borderRadius: BorderRadius.xxl,
    backgroundColor: 'rgba(201,150,58,0.12)',
    borderWidth: 1,
    borderColor: 'rgba(201,150,58,0.22)',
  },
  pbValueText: {
    color: Colors.textPrimary,
    fontSize: FontSize.lg,
    fontWeight: '900',
    fontVariant: ['tabular-nums'],
  },
  toolsRow: {
    flexDirection: 'row',
    gap: Spacing.md,
  },
  toolButton: {
    flex: 1,
    backgroundColor: '#161618',
    borderRadius: BorderRadius.xxl,
    borderWidth: 1,
    borderColor: Colors.borderDefault,
    paddingVertical: Spacing.xl,
    paddingHorizontal: Spacing.xl,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: Spacing.sm,
  },
  toolButtonDisabled: {
    opacity: 0.45,
  },
  toolLabel: {
    color: Colors.textPrimary,
    fontSize: FontSize.lg,
    fontWeight: '700',
  },
  toolLabelMuted: {
    color: Colors.textPlaceholder,
    fontSize: FontSize.lg,
    fontWeight: '600',
    textAlign: 'center',
  },
});
