import { BorderRadius, Colors, FontSize, Spacing } from '@/src/constants/theme';
import { StyleSheet } from 'react-native';

export const exerciseCardStyles = StyleSheet.create({
  card: {
    backgroundColor: '#151517',
    borderRadius: BorderRadius.xxl,
    padding: Spacing.xxl,
    marginBottom: Spacing.xxl,
    borderWidth: 1,
    borderColor: Colors.borderDefault,
    shadowColor: '#000000',
    shadowOpacity: 0.32,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 12 },
    elevation: 5,
  },
  header: {
    marginBottom: Spacing.xxl,
  },
  headerLeft: {
    flex: 1,
  },
  exerciseTitleRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: Spacing.md,
    marginBottom: Spacing.lg,
  },
  exerciseName: {
    color: Colors.textPrimary,
    fontSize: FontSize.displayXXXl,
    fontWeight: '900',
    letterSpacing: -0.8,
    lineHeight: 36,
  },
  pbSubtitle: {
    color: Colors.textMuted,
    fontSize: FontSize.md,
    fontWeight: '500',
    marginBottom: Spacing.xs,
  },
  additionalHeader: {
    color: Colors.accent,
    fontSize: FontSize.xs,
    fontWeight: '800',
    letterSpacing: 0.76,
    textTransform: 'uppercase',
  },
  additionalHeaderPill: {
    borderRadius: BorderRadius.xxl,
    borderWidth: 1,
    borderColor: 'rgba(201,150,58,0.22)',
    backgroundColor: Colors.accentSoft,
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.sm,
  },
  additionalDescription: {
    color: Colors.textSecondary,
    fontSize: FontSize.md,
    fontWeight: '600',
    marginBottom: Spacing.xs,
    marginTop: Spacing.xl,
  },
  repRangeLabel: {
    color: Colors.textSecondary,
    fontSize: FontSize.lg,
    fontWeight: '600',
    marginBottom: Spacing.xs,
  },
  amrapLabel: {
    color: Colors.accent,
    fontWeight: '800',
  },
  exerciseStatsRow: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: Colors.borderDefault,
    borderRadius: BorderRadius.xxl,
    backgroundColor: 'rgba(255,255,255,0.035)',
    marginBottom: Spacing.lg,
    overflow: 'hidden',
  },
  exerciseStatItem: {
    paddingVertical: Spacing.md,
    paddingHorizontal: Spacing.lg,
  },
  exerciseStatLabel: {
    color: Colors.textMuted,
    fontSize: FontSize.xs,
    fontWeight: '800',
    letterSpacing: 0.76,
    textTransform: 'uppercase',
    marginBottom: 2,
  },
  exerciseStatValue: {
    color: Colors.textPrimary,
    fontSize: FontSize.xl,
    fontWeight: '900',
    fontVariant: ['tabular-nums'],
  },
  exerciseStatDivider: {
    width: 1,
    alignSelf: 'stretch',
    backgroundColor: Colors.borderDefault,
  },
  setsHeader: {
    marginBottom: Spacing.xl,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  setsLabel: {
    color: Colors.textMuted,
    fontSize: FontSize.md,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  setControls: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: Colors.borderDefault,
    borderRadius: BorderRadius.xxl,
    backgroundColor: 'rgba(255,255,255,0.04)',
    overflow: 'hidden',
  },
  restTimerButton: {
    padding: Spacing.xs,
    borderWidth: 1,
    borderColor: Colors.borderDefault,
    borderRadius: BorderRadius.md,
  },
  setControlButton: {
    width: 38,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
  },
  setControlButtonDisabled: {
    opacity: 0.3,
  },
  setCountText: {
    color: Colors.textPrimary,
    fontSize: FontSize.xxl,
    fontWeight: '900',
    minWidth: 42,
    textAlign: 'center',
    fontVariant: ['tabular-nums'],
  },
  setTable: {
    borderWidth: 1,
    borderColor: Colors.borderDefault,
    borderRadius: BorderRadius.xxl,
    overflow: 'hidden',
    backgroundColor: 'rgba(255,255,255,0.025)',
  },
  setTableHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
    paddingHorizontal: Spacing.md,
    paddingTop: Spacing.md,
    paddingBottom: Spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: Colors.borderDefault,
  },
  setTableRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: Spacing.md,
    paddingHorizontal: Spacing.md,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.045)',
  },
  setTableRowDone: {
    backgroundColor: 'rgba(201,150,58,0.045)',
  },
  setNumberHeader: {
    width: 34,
    marginBottom: 0,
  },
  setNumberCell: {
    width: 34,
    alignItems: 'center',
    justifyContent: 'center',
  },
  setNumberText: {
    color: Colors.textMuted,
    fontSize: FontSize.lg,
    fontWeight: '900',
    fontVariant: ['tabular-nums'],
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
    flex: 1,
    marginBottom: 0,
  },
  inputGroup: {
    flex: 1,
  },
  inputGroupRepsOrTime: {
    flex: 1,
  },
  inputGroupGoldButton: {
    backgroundColor: Colors.accent,
  },
  inputGroupWithCheckmark: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
  },
  inputLabel: {
    color: Colors.textSecondary,
    fontSize: FontSize.md,
    fontWeight: '800',
    marginBottom: Spacing.md,
    textTransform: 'uppercase',
    letterSpacing: 0.96,
  },
  repsHeaderLabel: {
    flex: 1,
    marginBottom: 0,
  },
  input: {
    backgroundColor: 'rgba(255,255,255,0.045)',
    borderRadius: BorderRadius.xl,
    paddingVertical: Spacing.lg,
    paddingHorizontal: Spacing.xl,
    color: Colors.textPrimary,
    fontSize: FontSize.xxl,
    fontWeight: '800',
    borderWidth: 1,
    borderColor: Colors.borderDefault,
    fontVariant: ['tabular-nums'],
  },
  inputFocused: {
    borderColor: Colors.accent,
    shadowColor: Colors.accent,
    shadowOpacity: 0.35,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 0 },
    elevation: 3,
  },
  inputFlex: {
    flex: 1,
  },
  inputWithLeadingButtonRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
  },
  leadingIconButton: {
    width: 48,
    height: 48,
    borderRadius: BorderRadius.xl,
    backgroundColor: 'rgba(201,150,58,0.12)',
    borderWidth: 1,
    borderColor: 'rgba(201,150,58,0.28)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  leadingIconButtonDisabled: {
    opacity: 0.5,
  },
  inputButton: {
    borderColor: 'rgba(201,150,58,0.3)',
  },
  inputButtonText: {
    paddingVertical: 1,
    color: Colors.accent,
    fontWeight: '700',
    textAlign: 'center',
  },
  inputCompleted: {
    borderColor: Colors.accent,
    borderWidth: 1,
  },
  inputFailed: {
    borderColor: Colors.destructive,
    borderWidth: 1,
  },
  checkmarkButton: {
    width: 40,
    height: 44,
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkmarkButtonDisabled: {
    opacity: 0.3,
  },
  swapButtonContainer: {
    marginTop: Spacing.md,
  },
  swapButton: {
    paddingVertical: Spacing.xl,
    borderRadius: BorderRadius.xxl,
    borderWidth: 1,
    borderColor: 'rgba(201,150,58,0.34)',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(201,150,58,0.1)',
    shadowColor: Colors.accent,
    shadowOpacity: 0.14,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
  },
  swapButtonPressed: {
    transform: [{ scale: 0.98 }],
    backgroundColor: 'rgba(201,150,58,0.16)',
  },
  swapButtonText: {
    color: Colors.accent,
    fontSize: FontSize.lg,
    fontWeight: '800',
    letterSpacing: 0.2,
  },
  slotHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  slotLabel: {
    color: Colors.accent,
    fontSize: FontSize.md,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: Spacing.xs,
  },
});
