import { BorderRadius, Colors, FontSize, Spacing } from '@/src/constants/theme';
import { StyleSheet } from 'react-native';

export const swapModalStyles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: Colors.overlay,
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: Colors.backgroundCard,
    borderTopLeftRadius: BorderRadius.pill,
    borderTopRightRadius: BorderRadius.pill,
    padding: Spacing.section,
    maxHeight: '80%',
    borderWidth: 1,
    borderColor: Colors.borderDefault,
    flexDirection: 'column',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Spacing.xxl,
  },
  modalTitle: {
    color: Colors.textPrimary,
    fontSize: FontSize.displayXl,
    fontWeight: '700',
    flex: 1,
  },
  closeButton: {
    width: 32,
    height: 32,
    borderRadius: BorderRadius.full,
    backgroundColor: Colors.backgroundElevated,
    alignItems: 'center',
    justifyContent: 'center',
  },
  closeButtonText: {
    color: Colors.textPrimary,
    fontSize: FontSize.displaySm,
    fontWeight: '600',
  },
  modalSubtitle: {
    color: Colors.textMuted,
    fontSize: FontSize.lg,
    marginBottom: Spacing.xl,
    fontWeight: '500',
  },
  equipmentToggle: {
    alignSelf: 'flex-start',
    backgroundColor: Colors.backgroundElevated,
    borderRadius: BorderRadius.pill,
    paddingHorizontal: Spacing.xl,
    paddingVertical: Spacing.md,
    borderWidth: 1,
    borderColor: Colors.borderDefault,
    marginBottom: Spacing.xl,
  },
  equipmentToggleActive: {
    backgroundColor: Colors.accent,
    borderColor: Colors.accent,
  },
  equipmentToggleText: {
    color: Colors.textMuted,
    fontSize: FontSize.md,
    fontWeight: '700',
  },
  equipmentToggleTextActive: {
    color: Colors.textOnAccent,
  },
  disclaimer: {
    backgroundColor: Colors.accentOverlay,
    padding: Spacing.xl,
    borderRadius: BorderRadius.lg,
    fontSize: FontSize.md,
    marginBottom: Spacing.xxxl,
    fontWeight: '500',
    fontStyle: 'italic',
    lineHeight: 18,
  },
  deviationTitle: {
    color: Colors.textPrimary,
    fontSize: FontSize.lg,
    marginBottom: Spacing.xl,
    fontWeight: '500',
  },
  resetButton: {
    backgroundColor: Colors.backgroundElevated,
    borderRadius: BorderRadius.lg,
    padding: Spacing.xl,
    marginBottom: Spacing.xxl,
    borderWidth: 1,
    borderColor: Colors.accent,
    alignItems: 'center',
  },
  resetButtonText: {
    color: Colors.accent,
    fontSize: FontSize.xxl,
    fontWeight: '600',
  },
  alternativesList: {
    flexShrink: 1,
    minHeight: 200,
  },
  noAlternatives: {
    color: Colors.textMuted,
    fontSize: FontSize.lg,
    textAlign: 'center',
    padding: Spacing.xxxl,
  },
  alternativeItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: Colors.backgroundElevated,
    borderRadius: BorderRadius.xxl,
    padding: Spacing.xxl,
    marginBottom: Spacing.xl,
    borderWidth: 1,
    borderColor: Colors.borderSubtle,
  },
  alternativeContent: {
    flex: 1,
  },
  alternativeName: {
    color: Colors.textPrimary,
    fontSize: FontSize.displaySm,
    fontWeight: '700',
    marginBottom: Spacing.md,
  },
  alternativeMeta: {
    flexDirection: 'row',
    gap: Spacing.xl,
  },
  alternativeEquipment: {
    color: Colors.accent,
    fontSize: FontSize.md,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  alternativeMuscle: {
    color: Colors.textMuted,
    fontSize: FontSize.md,
    fontWeight: '500',
  },
  alternativeMatchScore: {
    color: Colors.textMuted,
    fontSize: FontSize.md,
    fontWeight: '500',
  },
  sectionTitle: {
    color: Colors.textPrimary,
    fontSize: FontSize.lg,
    fontWeight: '700',
    marginBottom: Spacing.lg,
    marginTop: Spacing.xl,
  },
  sectionHelperText: {
    color: Colors.textMuted,
    fontSize: FontSize.md,
    fontWeight: '500',
    marginBottom: Spacing.xl,
  },
  selectArrow: {
    color: Colors.accent,
    fontSize: FontSize.displayXl,
    fontWeight: '600',
    marginLeft: Spacing.xl,
  },
});
