import { BorderRadius, Colors, FontSize, Spacing } from '@/src/constants/theme';
import { StyleSheet } from 'react-native';

export const swapModalStyles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: Colors.overlay,
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: '#151517',
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
    padding: Spacing.section,
    maxHeight: '80%',
    borderWidth: 1,
    borderColor: Colors.borderDefault,
    flexDirection: 'column',
    shadowColor: '#000000',
    shadowOpacity: 0.36,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: -8 },
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Spacing.xxl,
  },
  modalTitle: {
    color: Colors.textPrimary,
    fontSize: FontSize.displayXXl,
    fontWeight: '900',
    letterSpacing: -0.5,
    flex: 1,
  },
  closeButton: {
    width: 32,
    height: 32,
    borderRadius: BorderRadius.xxl,
    backgroundColor: 'rgba(255,255,255,0.045)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  closeButtonText: {
    color: Colors.textPrimary,
    fontSize: FontSize.displaySm,
    fontWeight: '600',
  },
  modalSubtitle: {
    color: Colors.textMuted,
    fontSize: FontSize.lg,
    marginBottom: Spacing.xl,
    fontWeight: '500',
  },
  equipmentToggle: {
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(255,255,255,0.045)',
    borderRadius: BorderRadius.pill,
    paddingHorizontal: Spacing.xl,
    paddingVertical: Spacing.md,
    borderWidth: 1,
    borderColor: Colors.borderDefault,
    marginBottom: Spacing.xl,
  },
  equipmentToggleActive: {
    backgroundColor: Colors.accentSoft,
    borderColor: Colors.accent,
  },
  equipmentToggleText: {
    color: Colors.textMuted,
    fontSize: FontSize.md,
    fontWeight: '700',
  },
  equipmentToggleTextActive: {
    color: Colors.textPrimary,
  },
  disclaimer: {
    backgroundColor: Colors.accentOverlay,
    padding: Spacing.xl,
    borderRadius: BorderRadius.xxl,
    fontSize: FontSize.md,
    marginBottom: Spacing.xxxl,
    fontWeight: '500',
    fontStyle: 'italic',
    lineHeight: 18,
  },
  deviationTitle: {
    color: Colors.textPrimary,
    fontSize: FontSize.lg,
    marginBottom: Spacing.xl,
    fontWeight: '500',
  },
  resetButton: {
    backgroundColor: Colors.accentSoft,
    borderRadius: BorderRadius.xxl,
    padding: Spacing.xl,
    marginBottom: Spacing.xxl,
    borderWidth: 1,
    borderColor: Colors.accent,
    alignItems: 'center',
  },
  resetButtonText: {
    color: Colors.accent,
    fontSize: FontSize.xxl,
    fontWeight: '600',
  },
  alternativesList: {
    flexShrink: 1,
    minHeight: 200,
  },
  noAlternatives: {
    color: Colors.textMuted,
    fontSize: FontSize.lg,
    textAlign: 'center',
    padding: Spacing.xxxl,
  },
  alternativeItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'rgba(255,255,255,0.045)',
    borderRadius: BorderRadius.xxl,
    padding: Spacing.xxl,
    marginBottom: Spacing.xl,
    borderWidth: 1,
    borderColor: Colors.borderDefault,
  },
  alternativeContent: {
    flex: 1,
  },
  alternativeName: {
    color: Colors.textPrimary,
    fontSize: FontSize.displaySm,
    fontWeight: '900',
    marginBottom: Spacing.md,
  },
  alternativeMeta: {
    flexDirection: 'row',
    gap: Spacing.xl,
  },
  alternativeEquipment: {
    color: Colors.accent,
    fontSize: FontSize.md,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.96,
  },
  alternativeMuscle: {
    color: Colors.textMuted,
    fontSize: FontSize.md,
    fontWeight: '500',
  },
  alternativeMatchScore: {
    color: Colors.textMuted,
    fontSize: FontSize.md,
    fontWeight: '500',
  },
  sectionTitle: {
    color: Colors.textPrimary,
    fontSize: FontSize.lg,
    fontWeight: '700',
    marginBottom: Spacing.lg,
    marginTop: Spacing.xl,
  },
  sectionHelperText: {
    color: Colors.textMuted,
    fontSize: FontSize.md,
    fontWeight: '500',
    marginBottom: Spacing.xl,
  },
  selectArrow: {
    color: Colors.accent,
    fontSize: FontSize.displayXl,
    fontWeight: '600',
    marginLeft: Spacing.xl,
  },
});
