import { StyleSheet } from 'react-native';
import { BorderRadius, Colors, FontSize, Spacing } from '../constants/theme';

export const workoutTimerBarStyles = StyleSheet.create({
  bar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: Colors.timerBarBackground,
    borderBottomWidth: 1,
    borderBottomColor: Colors.borderDefault,
    paddingHorizontal: Spacing.xxl,
    paddingVertical: Spacing.xl,
    shadowColor: '#000000',
    shadowOpacity: 0.24,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
  },
  timerSection: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
    flex: 1,
    minWidth: 0,
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: Colors.accent,
  },
  timerText: {
    color: Colors.textPrimary,
    fontSize: FontSize.displaySm,
    fontWeight: '700',
    fontVariant: ['tabular-nums'],
  },
  finishButton: {
    backgroundColor: Colors.accentSoft,
    borderRadius: BorderRadius.xxl,
    paddingHorizontal: Spacing.xxl,
    paddingVertical: Spacing.md,
    borderWidth: 1,
    borderColor: 'rgba(201,150,58,0.34)',
  },
  finishButtonText: {
    color: Colors.accent,
    fontSize: FontSize.lg,
    fontWeight: '700',
    letterSpacing: 0.2,
  },
  iconButtonGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
  },
  iconButton: {
    backgroundColor: Colors.accentSoft,
    borderRadius: BorderRadius.xxl,
    alignItems: 'center',
    justifyContent: 'center',
  },
  adjustButton: {
    backgroundColor: 'rgba(255,255,255,0.045)',
    borderRadius: BorderRadius.xxl,
    borderWidth: 1,
    borderColor: Colors.borderDefault,
    alignItems: 'center',
    justifyContent: 'center',
  },
  adjustButtonText: {
    color: Colors.textPrimary,
    fontSize: FontSize.md,
    fontWeight: '800',
    fontVariant: ['tabular-nums'],
    letterSpacing: 0.2,
  },
  buttonSize: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 42,
    height: 42,
  },
});
