import { BorderRadius, Colors, FontSize, Spacing } from '@/src/constants/theme';
import { StyleSheet } from 'react-native';

export const partnerDiscoverMapStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.backgroundScreen,
  },
  map: {
    flex: 1,
  },
  clusterBubble: {
    minWidth: 48,
    height: 48,
    borderRadius: 24,
    paddingHorizontal: Spacing.md,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.accent,
    borderWidth: 3,
    borderColor: Colors.backgroundScreen,
  },
  clusterCount: {
    color: Colors.textOnAccent,
    fontSize: FontSize.displayMd,
    fontWeight: '800',
    lineHeight: 22,
  },
  markerWrap: {
    alignItems: 'center',
    maxWidth: 200,
  },
  markerLabel: {
    color: Colors.textPrimary,
    fontSize: FontSize.lg,
    fontWeight: '700',
    textAlign: 'center',
    marginTop: Spacing.sm,
    backgroundColor: 'rgba(18, 18, 18, 0.92)',
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.xs,
    borderRadius: BorderRadius.sm,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
  },
  markerLabelHidden: {
    opacity: 0,
    maxHeight: 0,
    marginTop: 0,
    paddingVertical: 0,
    paddingHorizontal: 0,
  },
  markerDot: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: Colors.accent,
    borderWidth: 3,
    borderColor: Colors.backgroundScreen,
  },
  emptyState: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: Spacing.section,
    gap: Spacing.md,
  },
  emptyTitle: {
    color: Colors.textPrimary,
    fontSize: FontSize.xl,
    fontWeight: '700',
    textAlign: 'center',
  },
  emptyDescription: {
    color: Colors.textMuted,
    fontSize: FontSize.lg,
    lineHeight: 22,
    textAlign: 'center',
  },
  attribution: {
    position: 'absolute',
    right: Spacing.md,
    bottom: Spacing.md,
    color: Colors.textPrimary,
    fontSize: FontSize.xxs,
    fontWeight: '600',
    backgroundColor: 'rgba(18, 18, 18, 0.82)',
    paddingHorizontal: Spacing.sm,
    paddingVertical: 2,
    borderRadius: BorderRadius.sm,
    overflow: 'hidden',
  },
});
