import { BorderRadius, Colors, FontSize, Spacing } from '@/src/constants/theme';
import { StyleSheet } from 'react-native';

export const logFormModalStyles = StyleSheet.create({
  modalKeyboardRoot: {
    flex: 1,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: Colors.overlayLight,
    justifyContent: 'center',
    paddingHorizontal: Spacing.xxl,
    paddingVertical: Spacing.section,
  },
  modalCard: {
    backgroundColor: '#151517',
    borderRadius: BorderRadius.xxl,
    borderWidth: 1,
    borderColor: Colors.borderDefault,
    maxHeight: '90%',
    paddingBottom: Spacing.xxl,
    paddingHorizontal: Spacing.xxl,
    paddingTop: Spacing.xxl,
    shadowColor: '#000000',
    shadowOpacity: 0.32,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 12 },
    elevation: 5,
  },
  modalHeaderRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: Spacing.xxl,
  },
  modalHeaderText: {
    flex: 1,
    paddingRight: Spacing.md,
  },
  modalCloseBtn: {
    width: 44,
    height: 44,
    borderRadius: BorderRadius.xxl,
    backgroundColor: 'rgba(255,255,255,0.045)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalTitle: {
    fontSize: FontSize.displayLg,
    fontWeight: '900',
    color: Colors.textPrimary,
    letterSpacing: -0.3,
  },
  modalSubtitle: {
    fontSize: FontSize.lg,
    lineHeight: 22,
    color: Colors.textMuted,
    marginTop: Spacing.sm,
  },
  modalScroll: {
    maxHeight: 400,
  },
  modalScrollContent: {
    paddingBottom: Spacing.xl,
  },
  whenBlock: {
    marginBottom: Spacing.xxl,
    paddingBottom: Spacing.xxl,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: Colors.borderDefault,
  },
  whenHint: {
    fontSize: FontSize.base,
    lineHeight: 20,
    color: Colors.textMuted,
    marginBottom: Spacing.md,
  },
  whenSingleLine: {
    fontSize: FontSize.lg,
    color: Colors.textSecondary,
    fontWeight: '500',
    marginBottom: Spacing.md,
  },
  whenButton: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    paddingVertical: Spacing.sm,
    paddingHorizontal: Spacing.lg,
    borderRadius: BorderRadius.xxl,
    borderWidth: 1,
    borderColor: Colors.borderDefault,
    backgroundColor: 'rgba(255,255,255,0.045)',
    gap: Spacing.sm,
  },
  whenButtonText: {
    fontSize: FontSize.base,
    fontWeight: '600',
    color: Colors.accent,
  },
  whenPickerOverlayAbsolute: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    backgroundColor: Colors.overlayLight,
    justifyContent: 'flex-end',
    zIndex: 1000,
  },
  whenPickerSheet: {
    backgroundColor: '#151517',
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
    paddingBottom: Spacing.xxl,
  },
  whenPickerToolbar: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    paddingHorizontal: Spacing.xxl,
    paddingVertical: Spacing.md,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: Colors.borderDefault,
  },
  whenPickerDone: {
    fontSize: FontSize.xl,
    fontWeight: '700',
    color: Colors.accent,
  },
  fieldLabel: {
    fontSize: FontSize.lg,
    fontWeight: '800',
    color: Colors.accent,
    marginBottom: Spacing.md,
  },
  fieldHint: {
    fontWeight: '400',
    color: Colors.textMuted,
    fontSize: FontSize.base,
  },
  input: {
    borderWidth: 1,
    borderColor: Colors.borderDefault,
    borderRadius: BorderRadius.xxl,
    paddingHorizontal: Spacing.xxl,
    paddingVertical: Spacing.xxl,
    fontSize: FontSize.displaySm,
    color: Colors.textPrimary,
    marginBottom: Spacing.xxl,
    backgroundColor: 'rgba(255,255,255,0.045)',
    fontWeight: '700',
  },
  inputSessionNotes: {
    fontSize: FontSize.base,
    lineHeight: 20,
  },
  textArea: {
    minHeight: 100,
    textAlignVertical: 'top',
  },
  textAreaSmall: {
    minHeight: 72,
    textAlignVertical: 'top',
  },
  modalActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginTop: Spacing.xxl,
    marginBottom: Spacing.xs,
    gap: Spacing.md,
  },
  btnGhostLarge: {
    flex: 1,
    paddingVertical: Spacing.xxl,
    paddingHorizontal: Spacing.xxl,
    borderRadius: BorderRadius.xxl,
    borderWidth: 1,
    borderColor: Colors.borderDefault,
    backgroundColor: 'rgba(255,255,255,0.045)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  btnGhostText: {
    fontSize: FontSize.xl,
    color: Colors.textSecondary,
    fontWeight: '600',
  },
  btnPrimaryLarge: {
    flex: 1,
    flexDirection: 'row',
    paddingVertical: Spacing.xxl,
    paddingHorizontal: Spacing.xxl,
    borderRadius: BorderRadius.xxl,
    backgroundColor: Colors.accentSoft,
    borderWidth: 1,
    borderColor: 'rgba(201,150,58,0.34)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  btnPrimaryIcon: {
    marginRight: Spacing.sm,
  },
  btnPrimaryText: {
    fontSize: FontSize.xl,
    color: Colors.accent,
    fontWeight: '700',
  },
  keyboardDoneBar: {
    position: 'absolute',
    left: 0,
    right: 0,
    zIndex: 10,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(15,15,17,0.96)',
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: Colors.borderDefault,
    paddingHorizontal: Spacing.xxl,
    paddingVertical: Spacing.lg,
  },
  keyboardDoneBarSpacer: {
    flex: 1,
  },
  keyboardDoneBtn: {
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.sm,
  },
  keyboardDoneText: {
    color: Colors.accent,
    fontSize: FontSize.xl,
    fontWeight: '700',
  },
});
