import { BorderRadius, Colors, FontSize, Spacing } from '@/src/constants/theme';
import { StyleSheet } from 'react-native';

export const onboardingStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.backgroundScreen,
  },
  header: {
    paddingHorizontal: Spacing.xxl,
    paddingTop: Spacing.xxl,
    paddingBottom: Spacing.xl,
    gap: Spacing.xl,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: Spacing.xl,
  },
  progressRow: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
  },
  progressTrack: {
    flex: 1,
    height: 4,
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderRadius: BorderRadius.pill,
    overflow: 'hidden',
  },
  progressFill: {
    height: 4,
    backgroundColor: Colors.accent,
    borderRadius: BorderRadius.pill,
  },
  progressText: {
    color: Colors.textMuted,
    fontSize: FontSize.md,
    fontWeight: '700',
    letterSpacing: 0.5,
    minWidth: 56,
    textAlign: 'right',
  },
  skipSetupButton: {
    paddingVertical: Spacing.sm,
  },
  skipSetupText: {
    color: Colors.textMuted,
    fontSize: FontSize.base,
    fontWeight: '600',
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    padding: Spacing.xxl,
    paddingTop: Spacing.xl,
    paddingBottom: Spacing.section,
    flexGrow: 1,
  },
  stepBody: {
    flex: 1,
    gap: Spacing.xl,
  },
  stepTitle: {
    color: Colors.textPrimary,
    fontSize: FontSize.hero,
    fontWeight: '900',
    letterSpacing: -1.1,
  },
  stepSubtitle: {
    color: Colors.textMuted,
    fontSize: FontSize.xxl,
    fontWeight: '500',
    lineHeight: 22,
  },
  textInput: {
    backgroundColor: 'rgba(255,255,255,0.045)',
    borderRadius: BorderRadius.xxl,
    borderWidth: 1,
    borderColor: Colors.borderDefault,
    paddingHorizontal: Spacing.xxl,
    paddingVertical: Spacing.xxl,
    color: Colors.textPrimary,
    fontSize: FontSize.displaySm,
    fontWeight: '600',
  },
  optionList: {
    gap: Spacing.md,
  },
  optionListInline: {
    gap: Spacing.md,
    flexWrap: 'wrap',
    flexDirection: 'row',
  },
  optionCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#151517',
    borderRadius: BorderRadius.xxl,
    paddingHorizontal: Spacing.xxl,
    paddingVertical: Spacing.xxl,
    borderWidth: 1,
    borderColor: Colors.borderDefault,
    shadowColor: '#000000',
    shadowOpacity: 0.18,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 2,
  },
  optionCardSelected: {
    borderColor: Colors.accent,
    backgroundColor: Colors.accentSoft,
  },
  optionCardNotFullWidth: {
    alignSelf: 'flex-start',
  },
  optionLabelNotFullWidth: {
    flex: 0,
  },
  optionLabel: {
    color: Colors.textPrimary,
    fontSize: FontSize.displaySm,
    fontWeight: '700',
    flex: 1,
  },
  optionLabelSelected: {
    color: Colors.accent,
  },
  optionCheckSlot: {
    width: 24,
    height: 24,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: Spacing.md,
  },
  optionCheck: {
    color: Colors.accent,
    fontSize: FontSize.displayLg,
    fontWeight: '800',
    lineHeight: 24,
  },
  iCloudCard: {
    backgroundColor: '#151517',
    borderRadius: BorderRadius.xxl,
    padding: Spacing.xxl,
    borderWidth: 1,
    borderColor: Colors.borderDefault,
    shadowColor: '#000000',
    shadowOpacity: 0.18,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 2,
    gap: Spacing.md,
  },
  iCloudTitle: {
    color: Colors.textPrimary,
    fontSize: FontSize.displaySm,
    fontWeight: '700',
  },
  iCloudDescription: {
    color: Colors.textMuted,
    fontSize: FontSize.lg,
    lineHeight: 20,
  },
  iCloudRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: Spacing.md,
  },
  iCloudToggleLabel: {
    color: Colors.textPrimary,
    fontSize: FontSize.xxl,
    fontWeight: '700',
  },
  iCloudUnavailable: {
    color: Colors.textPlaceholder,
    fontSize: FontSize.md,
    fontStyle: 'italic',
    marginTop: Spacing.sm,
  },
  finalCard: {
    backgroundColor: '#151517',
    borderRadius: BorderRadius.xxl,
    padding: Spacing.xxl,
    borderWidth: 1,
    borderColor: Colors.borderDefault,
    shadowColor: '#000000',
    shadowOpacity: 0.22,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 9 },
    elevation: 3,
    gap: Spacing.lg,
  },
  finalCardTitle: {
    color: Colors.textPrimary,
    fontSize: FontSize.displaySm,
    fontWeight: '800',
    letterSpacing: -0.2,
  },
  finalBullets: {
    gap: Spacing.md,
  },
  finalBullet: {
    color: Colors.textMuted,
    fontSize: FontSize.xxl,
    fontWeight: '600',
    lineHeight: 24,
  },
  finalActions: {
    gap: Spacing.md,
  },
  finalActionPrimary: {
    backgroundColor: Colors.accentSoft,
    borderRadius: BorderRadius.xxl,
    paddingVertical: Spacing.xxl,
    paddingHorizontal: Spacing.xxl,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(201,150,58,0.34)',
  },
  finalActionPrimaryText: {
    color: Colors.accent,
    fontSize: FontSize.xxl,
    fontWeight: '800',
    letterSpacing: 0.2,
  },
  finalActionSecondary: {
    backgroundColor: 'rgba(255,255,255,0.045)',
    borderRadius: BorderRadius.xxl,
    paddingVertical: Spacing.xl,
    paddingHorizontal: Spacing.xxl,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: Colors.borderDefault,
  },
  finalActionSecondaryText: {
    color: Colors.textPrimary,
    fontSize: FontSize.xxl,
    fontWeight: '700',
  },
  finalFinePrint: {
    color: Colors.textMuted,
    fontSize: FontSize.lg,
    fontWeight: '600',
    textAlign: 'center',
  },
  footer: {
    paddingHorizontal: Spacing.xxl,
    paddingTop: Spacing.xl,
    gap: Spacing.md,
    borderTopWidth: 1,
    borderTopColor: Colors.borderDefault,
  },
  footerSecondaryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  primaryButton: {
    backgroundColor: Colors.accentSoft,
    borderRadius: BorderRadius.xxl,
    paddingVertical: Spacing.xxl,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(201,150,58,0.34)',
  },
  primaryButtonDisabled: {
    opacity: 0.4,
  },
  primaryButtonText: {
    color: Colors.accent,
    fontSize: FontSize.xxl,
    fontWeight: '700',
    letterSpacing: 0.2,
  },
  skipStepButton: {
    alignSelf: 'center',
    paddingVertical: Spacing.md,
  },
  backStepButton: {
    paddingVertical: Spacing.md,
  },
  skipStepText: {
    color: Colors.textMuted,
    fontSize: FontSize.lg,
    fontWeight: '600',
  },
});
